timeout: 4800s
steps:
- name: hashicorp/packer
  id: VALIDATE
  args:
  - validate
  - template.json  
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD
  timeout: 2400s
  waitFor:
  - VALIDATE
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=PACKER_CACHE_DIR=/var/tmp/packer_cache packer build /home/packer/workspace/template.json
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUSH
  timeout: 2400s
  waitFor:
  - BUILD
  env:
    - ATLAS_TOKEN=${_TOKEN}
  args:
  - 'cloud'
  - 'publish'
  - 'alvaro/supertest'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-vbox.box'
  - '--release'
  - '--force'
substitutions:
  _TOKEN: TOKEN # default value
