timeout: 9000s
steps:
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64
  timeout: 3000s
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=PACKER_CACHE_DIR=/var/tmp/packer_cache time packer build -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64.json
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64
  env:
    - ATLAS_TOKEN=${_TOKEN}
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-vbox.box'
  - '--release'
  - '--force'
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64-NGINX
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=PACKER_CACHE_DIR=/var/tmp/packer_cache time packer build -var "build_name=bionic64-nginx" -var "packages=nginx" -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64-ovf.json  
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64-NGINX
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64-NGINX
  env:
    - ATLAS_TOKEN=${_TOKEN}
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64-nginx'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-nginx-vbox.box'
  - '--release'
  - '--force'
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64-REDIS
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=PACKER_CACHE_DIR=/var/tmp/packer_cache time packer build -var "build_name=bionic64-redis" -var "packages=redis-server redis-tools" -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64-ovf.json  
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64-REDIS
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64-REDIS
  env:
    - ATLAS_TOKEN=${_TOKEN}
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64-redis'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-redis-vbox.box'
  - '--release'
  - '--force' 
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64-DEV
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=PACKER_CACHE_DIR=/var/tmp/packer_cache time packer build -var "build_name=bionic64-dev" -var "packages=git curl wget build-essential" -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64-ovf.json  
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64-DEV
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64-DEV
  env:
    - ATLAS_TOKEN=${_TOKEN}
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64-dev'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-dev-vbox.box'
  - '--release'
  - '--force'   
substitutions:
  _TOKEN: TOKEN # default value
