timeout: 9000s
steps:
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64-NGINX
  timeout: 3000s
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=packer build -var "build_name=bionic64-nginx" -var "packages=nginx" -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64-vagrant.json
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64-NGINX
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64-NGINX
  env:
    - ATLAS_TOKEN=
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64-nginx'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-nginx/package.box'
  - '--release'
  - '--force'
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64-JRE
  timeout: 3000s
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=packer build -var "build_name=bionic64-jre" -var "packages=default-jre" -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64-vagrant.json
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64-JRE
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64-JRE
  env:
    - ATLAS_TOKEN=
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64-jre'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-jre/package.box'
  - '--release'
  - '--force'
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64-JDK
  timeout: 3000s
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=packer build -var "build_name=bionic64-jdk" -var "packages=default-jdk" -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64-vagrant.json
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64-JDK
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64-JDK
  env:
    - ATLAS_TOKEN=
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64-jdk'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-jdk/package.box'
  - '--release'
  - '--force'
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64-MYSQL
  timeout: 3000s
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=packer build -var "build_name=bionic64-mysql" -var "packages=mysql-server" -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64-vagrant.json
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64-MYSQL
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64-MYSQL
  env:
    - ATLAS_TOKEN=
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64-mysql'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-mysql/package.box'
  - '--release'
  - '--force'
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64-REDIS
  timeout: 3000s
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=packer build -var "build_name=bionic64-redis" -var "packages=redis-server redis-tools" -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64-vagrant.json
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64-REDIS
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64-REDIS
  env:
    - ATLAS_TOKEN=
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64-redis'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-redis/package.box'
  - '--release'
  - '--force'
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64-PHP
  timeout: 3000s
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=packer build -var "build_name=bionic64-php" -var "packages=nginx php php-fpm" -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64-vagrant.json
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64-PHP
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64-PHP
  env:
    - ATLAS_TOKEN=
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64-php'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-php/package.box'
  - '--release'
  - '--force'
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64-DEV
  timeout: 3000s
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=packer build -var "build_name=bionic64-dev" -var "packages=git curl wget build-essential" -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64-vagrant.json
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64-DEV
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64-DEV
  env:
    - ATLAS_TOKEN=
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64-dev'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-dev/package.box'
  - '--release'
  - '--force'
- name: gcr.io/$PROJECT_ID/remote-builder
  id: BUILD-BIONIC64-DOCKER
  timeout: 3000s
  waitFor: ["-"]
  env:
    - INSTANCE_ARGS=--image nestedvbox --machine-type=n1-standard-2 --preemptible --boot-disk-type=pd-ssd --boot-disk-size=50GB
    - ZONE=europe-west4-a
    - USERNAME=packer
    - COMMAND=packer build -var "build_name=bionic64-docker" -var "packages=docker.io" -var "wd=/home/packer/workspace" /home/packer/workspace/bionic64-vagrant.json
- name: gcr.io/$PROJECT_ID/vagrant
  id: PUBLISH-BIONIC64-DOCKER
  timeout: 3000s
  waitFor:
  - BUILD-BIONIC64-DOCKER
  env:
    - ATLAS_TOKEN=
  args:
  - 'cloud'
  - 'publish'
  - 'kikitux/bionic64-docker'
  - '$TAG_NAME'
  - 'virtualbox'
  - 'bionic64-docker/package.box'
  - '--release'
  - '--force'
substitutions:
  _TOKEN: TOKEN # default value
